#!/usr/bin/env bash
# A Bash script that transfers a file from a client to a server:

# Check if at least 4 arguments are passed to the script
if [[ "$#" -lt 4 ]]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi
